DAOS-10600 rpm: Update UCX RPM to 1.12
daos-stack/openucx pull request #3
Opened 2022-05-14 00:06 UTC by kjacque

Updated the specfile to pull and build UCX v1.12. Based the update
on the CentOS8 version of the UCX v1.11 specfile.

Signed-off-by: Kris Jacque <kristin.jacque@intel.com>

2022-05-14 00:07 UTC, kjacque commented
Tested this on Rocky8.5, was able to build and install the RPMs, and DAOS interacted with them correctly.

Haven't tested on EL7 or SUSE/Leap yet.

2022-05-16 16:16 UTC, brianjmurrell commented
You will want to add `el8` to the list of distros in `Jenkinsfile` and perhaps remove `leap15` until you are ready to try porting the specfile to leap15.

2022-05-17 15:54 UTC, kjacque commented
With some small tweaks, I've got the RPM building on Leap15 and CentOS7.9.

2022-05-20 15:42 UTC, brianjmurrell requested changes
Try removing https://github.com/daos-stack/openucx/blob/c4a7743b08ae42266bcdfe1f9246e7f0e3c2be7e/packaging/Makefile_packaging.mk#L101-L105 and see if that fixes the Test stage.

2022-05-20 15:42 UTC, brianjmurrell commented on ucx.spec
> +%changelog
Line 23 says the version is `Version: 1.12.1`.  Do you need an entry in this `%changelog`?

2022-05-20 18:22 UTC, kjacque commented on ucx.spec
> +%changelog
Added he changelog. Your script change let it pass the test stage, too. Thanks!

2022-05-24 16:35 UTC, brianjmurrell requested changes
Looks good.  Can I ask you to rebase the `packaging/` subdir on `bmurrell/remove-repo-install` as the formal fix for that problem to ensure that it all still passes here and then I can get that landed?  Much thanks.

2022-05-24 18:46 UTC, brianjmurrell approved these changes

2022-05-25 11:53 UTC, brianjmurrell commented
@kjacque requested landing in Skype.

2022-05-25 11:54 UTC, merged