DAOS-10674 build: Add Ubuntu to build
daos-stack/openucx pull request #4
Opened 2022-06-01 22:30 UTC by jolivier23

Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

2022-06-02 23:09 UTC, jolivier23 commented
@brianjmurrell I may need some help figuring out what to change on this.

2022-06-03 12:15 UTC, brianjmurrell requested changes

2022-06-03 12:15 UTC, brianjmurrell commented on ucx.spec
> +           --prefix=%{_prefix} \
The `%configure` macro will include this itself.

```suggestion
```

2022-06-03 12:15 UTC, brianjmurrell commented on ucx.spec
> +make DESTDIR=%{buildroot} install prefix=%{_prefix} libdir=%{_libdir} datadir=%{_datadir}
These shouldn't be necessary.  IIUC the RPM builds were already working correctly so probably nothing in this file needs updating.

```suggestion
make DESTDIR=%{buildroot} install
```

2022-06-03 12:15 UTC, brianjmurrell commented on ucx.spec
> +rm -f %{buildroot}%{_libdir}/*la
It really is only `.la` files we want to remove though, right?

```suggestion
rm -f %{buildroot}%{_libdir}/*.la
```

2022-06-03 12:15 UTC, brianjmurrell commented on ucx.spec
> +
I don't think anything in the RPM build needs updating.

```suggestion
```

2022-06-03 12:15 UTC, brianjmurrell commented on debian/patches/series
> +undo-upstream.patch
I wonder if this patch really does get applied.  Our debian builds actually take their patches from the specfile.  I'm not sure if we will apply patches from this dir if they exist.  I will check the build.

So, yeah, this is the problem.  If you add this patch to the RPM specfile, things should work better.

I suppose we really ought to handle this situation better.

2022-06-03 17:13 UTC, brianjmurrell submitted a review, later dismissed

2022-06-03 19:45 UTC, brianjmurrell requested changes

2022-06-03 19:45 UTC, brianjmurrell commented on debian/control
> -Breaks: libopenmpi3 ( << 4.1.0-3)
I'd rather see this commented out with a comment that **we** did that, not upstream, and why.  Just that in the future, we know.

2022-06-04 01:07 UTC, brianjmurrell approved these changes

2022-06-06 15:39 UTC, merged